import { useState, useEffect } from "react";
import { useLocation } from "wouter";
import { useQuery, useMutation } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { apiRequest, queryClient } from "@/lib/queryClient";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import {
  Play,
  Undo2,
  CheckCircle2,
  AlertTriangle,
  User,
  Globe,
  MessageSquare,
  Target,
  Sparkles,
  ArrowRight,
  Save,
  RotateCcw,
  Pencil,
} from "lucide-react";

const SNAPSHOT_KEY = "onboarding_tester_snapshot";

interface Snapshot {
  firstName: string;
  targetLanguage: string;
  nativeLanguage: string;
  difficultyLevel: string;
  onboardingCompleted: boolean;
}

interface DialogueStep {
  opener?: string;
  retry?: string;
  success?: string;
}

interface DialogueConfig {
  step1: { opener: string; retry: string };
  step2: { success: string; retry: string };
  step3: { success: string; retry: string };
  step4: { opener: string };
}

const STEP_META = [
  {
    step: 1,
    icon: User,
    label: "Step 1 — Name",
    dbKey: "step1" as const,
    fields: [
      { key: "opener" as const, label: "Opening message", hint: "Sent at the very start before the student responds" },
      { key: "retry" as const, label: "Retry (name unclear)", hint: "Sent when name can't be extracted" },
    ],
  },
  {
    step: 2,
    icon: Globe,
    label: "Step 2 — Target Language",
    dbKey: "step2" as const,
    fields: [
      { key: "success" as const, label: "Ask for language", hint: "Use {{name}} for student's name" },
      { key: "retry" as const, label: "Retry (language unclear)", hint: "Sent when a supported language can't be identified" },
    ],
  },
  {
    step: 3,
    icon: MessageSquare,
    label: "Step 3 — Native Language",
    dbKey: "step3" as const,
    fields: [
      { key: "success" as const, label: "Ask for native language", hint: "Use {{name}} for student's name" },
      { key: "retry" as const, label: "Retry (native language unclear)", hint: "Sent when native language extraction fails" },
    ],
  },
  {
    step: 4,
    icon: Target,
    label: "Step 4 — Learning Goal",
    dbKey: "step4" as const,
    fields: [
      { key: "opener" as const, label: "Ask for goal", hint: "Use {{name}} and {{language}}. Closing message is AI-generated by Gemini." },
    ],
  },
];

export function OnboardingTesterContent() {
  const [, navigate] = useLocation();
  const { toast } = useToast();
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null);
  const [testActive, setTestActive] = useState(false);
  const [dialogueDraft, setDialogueDraft] = useState<DialogueConfig | null>(null);
  const [editMode, setEditMode] = useState(false);

  useEffect(() => {
    const saved = localStorage.getItem(SNAPSHOT_KEY);
    if (saved) {
      try {
        const parsed = JSON.parse(saved);
        setSnapshot(parsed);
        setTestActive(true);
      } catch {
        localStorage.removeItem(SNAPSHOT_KEY);
      }
    }
  }, []);

  const { data: currentStatus, refetch: refetchStatus } = useQuery<Snapshot>({
    queryKey: ["/api/admin/onboarding/snapshot"],
    refetchOnWindowFocus: true,
  });

  const { data: dialogueData, refetch: refetchDialogue } = useQuery<{ dialogue: DialogueConfig; defaults: DialogueConfig }>({
    queryKey: ["/api/admin/onboarding/dialogue"],
  });

  useEffect(() => {
    if (dialogueData?.dialogue && !dialogueDraft) {
      setDialogueDraft(structuredClone(dialogueData.dialogue));
    }
  }, [dialogueData]);

  const startMutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest("POST", "/api/admin/onboarding/start-test", {});
      return res.json();
    },
    onSuccess: (data) => {
      const snap: Snapshot = data.snapshot;
      localStorage.setItem(SNAPSHOT_KEY, JSON.stringify(snap));
      localStorage.setItem("userName", "");
      setSnapshot(snap);
      setTestActive(true);
      refetchStatus();
      toast({ title: "Onboarding reset", description: "Navigating to chat — go through the full flow, then come back to restore." });
      setTimeout(() => navigate("/chat"), 600);
    },
    onError: () => toast({ variant: "destructive", title: "Reset failed", description: "Could not reset onboarding state." }),
  });

  const restoreMutation = useMutation({
    mutationFn: async (snap: Snapshot) => {
      const res = await apiRequest("POST", "/api/admin/onboarding/restore-test", snap);
      return res.json();
    },
    onSuccess: (_, snap) => {
      localStorage.removeItem(SNAPSHOT_KEY);
      localStorage.setItem("userName", snap.firstName);
      setSnapshot(null);
      setTestActive(false);
      queryClient.invalidateQueries({ queryKey: ["/api/admin/onboarding/snapshot"] });
      queryClient.invalidateQueries({ queryKey: ["/api/user"] });
      refetchStatus();
      toast({ title: "Preferences restored", description: `Welcome back, ${snap.firstName}.` });
    },
    onError: () => toast({ variant: "destructive", title: "Restore failed", description: "Could not restore preferences." }),
  });

  const saveMutation = useMutation({
    mutationFn: async (config: DialogueConfig) => {
      const res = await apiRequest("PUT", "/api/admin/onboarding/dialogue", config);
      return res.json();
    },
    onSuccess: (data) => {
      setDialogueDraft(structuredClone(data.dialogue));
      queryClient.invalidateQueries({ queryKey: ["/api/admin/onboarding/dialogue"] });
      refetchDialogue();
      setEditMode(false);
      toast({ title: "Dialogue saved", description: "New messages will be used in the next onboarding session." });
    },
    onError: () => toast({ variant: "destructive", title: "Save failed", description: "Could not save dialogue config." }),
  });

  const resetDialogueMutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest("POST", "/api/admin/onboarding/dialogue/reset", {});
      return res.json();
    },
    onSuccess: (data) => {
      setDialogueDraft(structuredClone(data.dialogue));
      queryClient.invalidateQueries({ queryKey: ["/api/admin/onboarding/dialogue"] });
      refetchDialogue();
      setEditMode(false);
      toast({ title: "Dialogue reset", description: "All messages restored to defaults." });
    },
    onError: () => toast({ variant: "destructive", title: "Reset failed" }),
  });

  const isDirty = dialogueDraft && dialogueData?.dialogue
    ? JSON.stringify(dialogueDraft) !== JSON.stringify(dialogueData.dialogue)
    : false;

  const isOnboardingCompleted = currentStatus?.onboardingCompleted !== false;

  function updateField(stepKey: keyof DialogueConfig, fieldKey: string, value: string) {
    if (!dialogueDraft) return;
    setDialogueDraft((prev) => {
      if (!prev) return prev;
      return {
        ...prev,
        [stepKey]: { ...(prev[stepKey] as Record<string, string>), [fieldKey]: value },
      };
    });
    setEditMode(true);
  }

  return (
    <div className="space-y-6 max-w-3xl">
      <div>
        <h2 className="text-xl font-semibold">Onboarding Tester</h2>
        <p className="text-muted-foreground text-sm mt-1">
          Preview and test-drive the new student onboarding flow. Edit the dialogue for any subject, then launch a live test — your preferences are always restored.
        </p>
      </div>

      {/* ── In-progress banner ── */}
      {testActive && snapshot && (
        <Card className="border-amber-200 dark:border-amber-800 bg-amber-50/50 dark:bg-amber-950/20">
          <CardContent className="pt-5 pb-4">
            <div className="flex items-start gap-3">
              <AlertTriangle className="w-5 h-5 text-amber-600 dark:text-amber-400 mt-0.5 shrink-0" />
              <div className="flex-1 min-w-0">
                <p className="font-medium text-sm text-amber-900 dark:text-amber-200">Test in progress</p>
                <p className="text-sm text-amber-700 dark:text-amber-400 mt-0.5">
                  Your real preferences are saved. Complete onboarding in the chat, then click Restore below.
                </p>
                <div className="flex flex-wrap gap-2 mt-3">
                  <Button size="sm" variant="outline" onClick={() => navigate("/chat")} data-testid="button-go-to-chat">
                    <Play className="w-3 h-3 mr-1.5" />
                    Go to Chat
                  </Button>
                  <AlertDialog>
                    <AlertDialogTrigger asChild>
                      <Button size="sm" data-testid="button-restore-preferences" disabled={restoreMutation.isPending}>
                        <Undo2 className="w-3 h-3 mr-1.5" />
                        {restoreMutation.isPending ? "Restoring…" : "Restore My Preferences"}
                      </Button>
                    </AlertDialogTrigger>
                    <AlertDialogContent>
                      <AlertDialogHeader>
                        <AlertDialogTitle>Restore your account?</AlertDialogTitle>
                        <AlertDialogDescription>
                          This will restore your original preferences:{" "}
                          <strong>{snapshot.firstName}</strong>,{" "}
                          <strong>{snapshot.targetLanguage || "no language set"}</strong>,{" "}
                          <strong>{snapshot.nativeLanguage || "no native language"}</strong>.
                          Any changes from the test run will be overwritten.
                        </AlertDialogDescription>
                      </AlertDialogHeader>
                      <AlertDialogFooter>
                        <AlertDialogCancel>Cancel</AlertDialogCancel>
                        <AlertDialogAction onClick={() => restoreMutation.mutate(snapshot)}>Restore</AlertDialogAction>
                      </AlertDialogFooter>
                    </AlertDialogContent>
                  </AlertDialog>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* ── Current Status ── */}
      <Card>
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between gap-2 flex-wrap">
            <div>
              <CardTitle className="text-base">Current Status</CardTitle>
              <CardDescription className="mt-0.5">Your account's onboarding state right now</CardDescription>
            </div>
            {currentStatus ? (
              isOnboardingCompleted ? (
                <Badge variant="secondary" className="gap-1.5">
                  <CheckCircle2 className="w-3 h-3" />
                  Onboarding complete
                </Badge>
              ) : (
                <Badge variant="outline" className="gap-1.5 text-amber-700 border-amber-300">
                  <AlertTriangle className="w-3 h-3" />
                  Onboarding pending
                </Badge>
              )
            ) : null}
          </div>
        </CardHeader>
        <CardContent>
          {currentStatus ? (
            <dl className="grid grid-cols-2 gap-x-6 gap-y-2 text-sm">
              <div>
                <dt className="text-muted-foreground">Name</dt>
                <dd className="font-medium">{currentStatus.firstName || <span className="text-muted-foreground italic">not set</span>}</dd>
              </div>
              <div>
                <dt className="text-muted-foreground">Target language</dt>
                <dd className="font-medium capitalize">{currentStatus.targetLanguage || <span className="text-muted-foreground italic">not set</span>}</dd>
              </div>
              <div>
                <dt className="text-muted-foreground">Native language</dt>
                <dd className="font-medium capitalize">{currentStatus.nativeLanguage || <span className="text-muted-foreground italic">not set</span>}</dd>
              </div>
              <div>
                <dt className="text-muted-foreground">Difficulty</dt>
                <dd className="font-medium capitalize">{currentStatus.difficultyLevel || <span className="text-muted-foreground italic">not set</span>}</dd>
              </div>
            </dl>
          ) : (
            <p className="text-sm text-muted-foreground">Loading…</p>
          )}

          {!testActive && (
            <div className="mt-5 pt-4 border-t">
              <AlertDialog>
                <AlertDialogTrigger asChild>
                  <Button data-testid="button-launch-onboarding-test" disabled={startMutation.isPending}>
                    <Play className="w-4 h-4 mr-2" />
                    {startMutation.isPending ? "Preparing test…" : "Launch Onboarding Test"}
                  </Button>
                </AlertDialogTrigger>
                <AlertDialogContent>
                  <AlertDialogHeader>
                    <AlertDialogTitle>Launch onboarding test?</AlertDialogTitle>
                    <AlertDialogDescription className="space-y-2">
                      <span className="block">
                        This will temporarily clear your name and language preferences so the full onboarding flow fires when you open the chat.
                      </span>
                      <span className="block">
                        Your real preferences are snapshotted and can be fully restored with the <strong>Restore</strong> button.
                      </span>
                    </AlertDialogDescription>
                  </AlertDialogHeader>
                  <AlertDialogFooter>
                    <AlertDialogCancel>Cancel</AlertDialogCancel>
                    <AlertDialogAction onClick={() => startMutation.mutate()}>Start test</AlertDialogAction>
                  </AlertDialogFooter>
                </AlertDialogContent>
              </AlertDialog>
              <p className="text-xs text-muted-foreground mt-2">
                After clicking, you'll be taken to /chat. Go through all 4 steps, then return here to restore your real preferences.
              </p>
            </div>
          )}
        </CardContent>
      </Card>

      {/* ── Dialogue Editor ── */}
      <div>
        <div className="flex items-center justify-between gap-2 mb-3 flex-wrap">
          <div className="flex items-center gap-2">
            <Pencil className="w-4 h-4 text-muted-foreground" />
            <h3 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground">Dialogue Script</h3>
          </div>
          <div className="flex items-center gap-2">
            {isDirty && (
              <Badge variant="outline" className="text-xs text-amber-700 border-amber-300">Unsaved changes</Badge>
            )}
            {editMode && (
              <AlertDialog>
                <AlertDialogTrigger asChild>
                  <Button size="sm" variant="outline" disabled={resetDialogueMutation.isPending}>
                    <RotateCcw className="w-3 h-3 mr-1.5" />
                    Reset to defaults
                  </Button>
                </AlertDialogTrigger>
                <AlertDialogContent>
                  <AlertDialogHeader>
                    <AlertDialogTitle>Reset all dialogue to defaults?</AlertDialogTitle>
                    <AlertDialogDescription>All custom messages will be lost.</AlertDialogDescription>
                  </AlertDialogHeader>
                  <AlertDialogFooter>
                    <AlertDialogCancel>Cancel</AlertDialogCancel>
                    <AlertDialogAction onClick={() => resetDialogueMutation.mutate()}>Reset</AlertDialogAction>
                  </AlertDialogFooter>
                </AlertDialogContent>
              </AlertDialog>
            )}
            {isDirty && (
              <Button size="sm" onClick={() => dialogueDraft && saveMutation.mutate(dialogueDraft)} disabled={saveMutation.isPending}>
                <Save className="w-3 h-3 mr-1.5" />
                {saveMutation.isPending ? "Saving…" : "Save changes"}
              </Button>
            )}
          </div>
        </div>
        <p className="text-xs text-muted-foreground mb-4">
          Edit any message and hit <strong>Save changes</strong>. Use{" "}
          <code className="bg-muted px-1 rounded">{"{{name}}"}</code> and{" "}
          <code className="bg-muted px-1 rounded">{"{{language}}"}</code> as placeholders.
          Changes take effect immediately on the next onboarding session.
        </p>

        {dialogueDraft ? (
          <div className="space-y-4">
            {STEP_META.map((meta) => {
              const Icon = meta.icon;
              const stepData = dialogueDraft[meta.dbKey] as Record<string, string>;
              const defaultStepData = dialogueData?.defaults?.[meta.dbKey] as Record<string, string> | undefined;
              return (
                <Card key={meta.step}>
                  <CardHeader className="pb-2 pt-4">
                    <div className="flex items-center gap-2">
                      <div className="w-7 h-7 rounded-full bg-muted flex items-center justify-center shrink-0">
                        <Icon className="w-3.5 h-3.5 text-muted-foreground" />
                      </div>
                      <CardTitle className="text-sm font-medium">{meta.label}</CardTitle>
                    </div>
                  </CardHeader>
                  <CardContent className="space-y-3 pb-4">
                    {meta.fields.map((field) => {
                      const currentVal = stepData[field.key] ?? "";
                      const defaultVal = defaultStepData?.[field.key] ?? "";
                      const isModified = currentVal !== defaultVal;
                      return (
                        <div key={field.key} className="space-y-1.5">
                          <div className="flex items-center gap-2">
                            <Label className="text-xs font-medium">{field.label}</Label>
                            {isModified && <Badge variant="outline" className="text-xs px-1.5 py-0">edited</Badge>}
                          </div>
                          <Textarea
                            value={currentVal}
                            onChange={(e) => updateField(meta.dbKey, field.key, e.target.value)}
                            className="text-sm min-h-[60px] resize-y"
                            data-testid={`textarea-dialogue-${meta.dbKey}-${field.key}`}
                          />
                          <p className="text-xs text-muted-foreground">{field.hint}</p>
                        </div>
                      );
                    })}
                  </CardContent>
                </Card>
              );
            })}
          </div>
        ) : (
          <p className="text-sm text-muted-foreground">Loading dialogue config…</p>
        )}

        <div className="mt-4 p-3 rounded-md bg-muted/50 text-xs text-muted-foreground">
          <strong>Step 4 closing message</strong> is always AI-generated by Gemini — it uses the student's name, target language, native language, and stated goal to write a personalised sign-off. It cannot be edited here, but you can tweak its prompt in{" "}
          <code className="bg-background px-1 rounded">server/routes.ts</code> (search <code className="bg-background px-1 rounded">closingPrompt</code>).
        </div>
      </div>
    </div>
  );
}
