/**
 * Curriculum Augmentor
 *
 * Adds thematic topic units to Level 3–5 curriculum paths that currently only
 * have generic "skill bucket" units (Intermediate High Skills, Advanced Low/Mid
 * Skills, etc.).
 *
 * New units are topic-focused and non-controversial:
 *   Level 3: Technology & Digital Life | Travel & Transportation | Health & Wellness
 *   Level 4: Business & Professional Life | Science & the Natural World | Arts, Cinema & Music
 *   Level 5: Financial Literacy & Economics | Media & Journalism | Cultural Heritage & Traditions
 *
 * Content is generated by Gemini in the target language to match the quality of
 * existing units. Already-present topic units are detected by keyword and skipped.
 *
 * startCurriculumAugmentor() runs once and exits when all paths are covered.
 */

import { GoogleGenAI } from '@google/genai';
import { getSharedDb } from '../db';
import { sql } from 'drizzle-orm';

// ── Gemini ──────────────────────────────────────────────────────────────────

let gemini: GoogleGenAI | null = null;
function getGemini() {
  if (!gemini) {
    gemini = new GoogleGenAI({
      apiKey: process.env.GEMINI_API_KEY || '',
      httpOptions: {
        apiVersion: '',
      },
    });
  }
  return gemini;
}

// ── Topic definitions ────────────────────────────────────────────────────────

interface TopicDef {
  name: string;
  description: string;
  keywords: string[];        // keywords to detect if this unit already exists
  actfl_levels: string[];    // actfl levels for lessons in this unit
  cultural_theme: string;
}

const LEVEL3_TOPICS: TopicDef[] = [
  {
    name: 'Technology & Digital Life',
    description: 'How digital technology shapes communication, work, study, and entertainment in the modern world.',
    keywords: ['technology', 'digital', 'technolog', 'internet', 'tech'],
    actfl_levels: ['intermediate_low', 'intermediate_mid'],
    cultural_theme: 'technology',
  },
  {
    name: 'Travel & Transportation',
    description: 'Navigating cities, planning trips, using public transit, and exploring destinations.',
    keywords: ['travel', 'transport', 'trip', 'viaje', 'voyage', 'reise', 'viaggio', 'transporte'],
    actfl_levels: ['intermediate_low', 'intermediate_mid'],
    cultural_theme: 'travel',
  },
  {
    name: 'Health & Wellness',
    description: 'Discussing personal health, nutrition, exercise routines, and healthy habits.',
    keywords: ['health', 'wellness', 'salud', 'santé', 'gesundheit', 'salute', 'saúde'],
    actfl_levels: ['intermediate_low', 'intermediate_mid'],
    cultural_theme: 'health',
  },
];

const LEVEL4_TOPICS: TopicDef[] = [
  {
    name: 'Business & Professional Life',
    description: 'Workplace communication, entrepreneurship, job interviews, and professional etiquette.',
    keywords: ['business', 'professional', 'entrepren', 'trabajo', 'travail', 'arbeit', 'lavoro', 'trabalho'],
    actfl_levels: ['intermediate_mid', 'intermediate_high'],
    cultural_theme: 'professional',
  },
  {
    name: 'Science & the Natural World',
    description: 'Exploring scientific discoveries, nature, geography, and how the natural world works.',
    keywords: ['science', 'natural', 'nature', 'ciencia', 'science', 'wissenschaft', 'scienza', 'ciência', 'natur'],
    actfl_levels: ['intermediate_mid', 'intermediate_high'],
    cultural_theme: 'science',
  },
  {
    name: 'Arts, Cinema & Music',
    description: 'Discussing films, music genres, visual arts, and the role of artistic expression in culture.',
    keywords: ['arts', 'cinema', 'music', 'arte', 'cine', 'música', 'film', 'kunst', 'musica', 'cinema'],
    actfl_levels: ['intermediate_mid', 'intermediate_high'],
    cultural_theme: 'arts',
  },
];

const LEVEL5_TOPICS: TopicDef[] = [
  {
    name: 'Financial Literacy & Economics',
    description: 'Personal finance, budgeting, global markets, economic systems, and financial decision-making.',
    keywords: ['financial', 'finance', 'economics', 'econom', 'finanzas', 'finances', 'wirtschaft', 'finanças'],
    actfl_levels: ['advanced_low', 'advanced_high'],
    cultural_theme: 'economics',
  },
  {
    name: 'Media, Journalism & Communication',
    description: 'How news is produced and consumed, media literacy, journalism ethics, and public discourse.',
    keywords: ['media', 'journalism', 'press', 'medios', 'presse', 'stampa', 'mídia', 'journalisme'],
    actfl_levels: ['advanced_low', 'advanced_high'],
    cultural_theme: 'media',
  },
  {
    name: 'Cultural Heritage & Traditions',
    description: 'Exploring literary traditions, festivals, historical legacy, and the preservation of culture.',
    keywords: ['heritage', 'tradition', 'patrimonio', 'patrimoine', 'erbe', 'patrimônio', 'tradición', 'héritage'],
    actfl_levels: ['advanced_low', 'advanced_high'],
    cultural_theme: 'heritage',
  },
];

const TOPICS_BY_LEVEL: Record<string, TopicDef[]> = {
  intermediate_low: LEVEL3_TOPICS,
  intermediate_mid: LEVEL4_TOPICS,
  advanced_low: LEVEL5_TOPICS,
};

// ── Language display names ───────────────────────────────────────────────────

const LANGUAGE_NAMES: Record<string, string> = {
  spanish: 'Spanish',
  french: 'French',
  german: 'German',
  italian: 'Italian',
  portuguese: 'Portuguese',
  japanese: 'Japanese',
  korean: 'Korean',
  mandarin: 'Mandarin Chinese',
  english: 'English',
};

const ACTFL_DISPLAY: Record<string, string> = {
  intermediate_low: 'Intermediate Low',
  intermediate_mid: 'Intermediate Mid',
  intermediate_high: 'Intermediate High',
  advanced_low: 'Advanced Low',
  advanced_high: 'Advanced High',
};

// ── Generated lesson shape ───────────────────────────────────────────────────

interface GeneratedLesson {
  name: string;
  lesson_type: 'conversation' | 'reading' | 'writing' | 'grammar' | 'cultural_exploration' | 'drill';
  actfl_level: string;
  conversation_topic: string;
  conversation_prompt: string;
  objectives: string[];
  estimated_minutes: number;
}

interface GeneratedUnit {
  unit: {
    name: string;
    description: string;
    cultural_theme: string;
  };
  lessons: GeneratedLesson[];
}

// ── Core generation ──────────────────────────────────────────────────────────

async function generateUnit(
  language: string,
  topicDef: TopicDef,
  pathLevel: string,
): Promise<GeneratedUnit | null> {
  const langDisplay = LANGUAGE_NAMES[language] || language;
  const actflDisplay = ACTFL_DISPLAY[pathLevel] || pathLevel;
  const [primaryLevel, secondaryLevel] = topicDef.actfl_levels;
  const primaryActfl = ACTFL_DISPLAY[primaryLevel] || primaryLevel;
  const secondaryActfl = ACTFL_DISPLAY[secondaryLevel] || secondaryLevel;

  const prompt = `You are a professional language curriculum writer. Generate a thematic learning unit for a ${langDisplay} language course at the ${actflDisplay} level (ACTFL framework).

Topic: ${topicDef.name}
Topic description: ${topicDef.description}

Create exactly 5 lessons in this order:
1. Conversation lesson (dialogue-based): students read an authentic dialogue in ${langDisplay}, then discuss
2. Conversation lesson (scenario/opinion): an open scenario or opinion-sharing exercise
3. Reading lesson: a short article or text IN ${langDisplay} (~250-350 words) on a real aspect of this topic
4. Writing lesson: a model paragraph or short essay in ${langDisplay} + writing task instructions
5. Cultural exploration lesson: a cultural angle connecting this topic to ${langDisplay}-speaking cultures

IMPORTANT RULES:
- ALL conversation_prompt content must be written IN ${langDisplay} (not English)
- Lesson names should be bilingual: "${langDisplay} Title (English Translation)"
- Keep content appropriate for high school students (ages 14-18)
- Avoid political controversy, social justice debates, or divisive topics
- Focus on practical, intellectually engaging, and culturally rich content
- Lessons 1-4 use actfl_level: "${primaryActfl}", lesson 5 uses "${secondaryActfl}"

Return ONLY valid JSON in this exact structure:
{
  "unit": {
    "name": "${topicDef.name}",
    "description": "2-sentence description of what students will learn",
    "cultural_theme": "${topicDef.cultural_theme}"
  },
  "lessons": [
    {
      "name": "Target language title (English translation)",
      "lesson_type": "conversation",
      "actfl_level": "${primaryLevel}",
      "conversation_topic": "Brief bilingual topic description",
      "conversation_prompt": "Rich content IN ${langDisplay} — full dialogue, scenario, or text (150-300 words)",
      "objectives": ["Objective 1", "Objective 2"],
      "estimated_minutes": 25
    },
    ... (5 lessons total, lesson 5 has lesson_type "cultural_exploration")
  ]
}`;

  try {
    const ai = getGemini();
    const result = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
      config: {
        temperature: 0.7,
        responseMimeType: 'application/json',
      },
    });

    const text = result.text?.trim() || '';
    const parsed = JSON.parse(text) as GeneratedUnit;

    if (!parsed.unit || !Array.isArray(parsed.lessons) || parsed.lessons.length === 0) {
      console.error(`[CurriculumAugmentor] Invalid response shape for ${language}/${topicDef.name}`);
      return null;
    }

    return parsed;
  } catch (err) {
    console.error(`[CurriculumAugmentor] Generation failed for ${language}/${topicDef.name}:`, err);
    return null;
  }
}

// ── DB helpers ───────────────────────────────────────────────────────────────

async function getExistingUnits(pathId: string): Promise<string[]> {
  const db = getSharedDb();
  const rows = await db.execute(sql`
    SELECT name FROM curriculum_units WHERE curriculum_path_id = ${pathId}
  `);
  return rows.rows.map((r: any) => (r.name as string).toLowerCase());
}

async function getMaxUnitOrder(pathId: string): Promise<number> {
  const db = getSharedDb();
  const rows = await db.execute(sql`
    SELECT COALESCE(MAX(order_index), 0) as max_order
    FROM curriculum_units WHERE curriculum_path_id = ${pathId}
  `);
  return Number((rows.rows[0] as any)?.max_order ?? 0);
}

async function insertUnit(
  pathId: string,
  topicDef: TopicDef,
  generated: GeneratedUnit,
  orderIndex: number,
  pathLevel: string,
): Promise<string> {
  const db = getSharedDb();

  const actflLevel = pathLevel === 'intermediate_low'
    ? 'intermediate_mid'
    : pathLevel === 'intermediate_mid'
      ? 'intermediate_high'
      : 'advanced_high';

  const unitResult = await db.execute(sql`
    INSERT INTO curriculum_units (
      id, curriculum_path_id, name, description, order_index,
      actfl_level, cultural_theme, estimated_hours, created_at, updated_at
    ) VALUES (
      gen_random_uuid(),
      ${pathId},
      ${generated.unit.name},
      ${generated.unit.description},
      ${orderIndex},
      ${actflLevel},
      ${generated.unit.cultural_theme},
      2,
      NOW(), NOW()
    )
    RETURNING id
  `);

  return (unitResult.rows[0] as any).id as string;
}

async function insertLessons(
  unitId: string,
  lessons: GeneratedLesson[],
): Promise<void> {
  const db = getSharedDb();
  for (let i = 0; i < lessons.length; i++) {
    const l = lessons[i];
    await db.execute(sql`
      INSERT INTO curriculum_lessons (
        id, curriculum_unit_id, name, description,
        order_index, lesson_type, actfl_level,
        conversation_topic, conversation_prompt,
        objectives, estimated_minutes,
        created_at, updated_at
      ) VALUES (
        gen_random_uuid(),
        ${unitId},
        ${l.name},
        ${l.conversation_topic || ''},
        ${i + 1},
        ${l.lesson_type},
        ${l.actfl_level},
        ${l.conversation_topic || ''},
        ${l.conversation_prompt || ''},
        ARRAY(SELECT jsonb_array_elements_text(${JSON.stringify(l.objectives || [])}::jsonb)),
        ${l.estimated_minutes || 25},
        NOW(), NOW()
      )
    `);
  }
  // Always add a drill lesson at the end
  await db.execute(sql`
    INSERT INTO curriculum_lessons (
      id, curriculum_unit_id, name, description,
      order_index, lesson_type, actfl_level,
      conversation_topic, conversation_prompt,
      objectives, estimated_minutes,
      created_at, updated_at
    ) VALUES (
      gen_random_uuid(),
      ${unitId},
      'Active Practice: Mixed Drills',
      'Reinforce vocabulary and structures from this unit',
      ${lessons.length + 1},
      'drill',
      ${lessons[0]?.actfl_level || 'intermediate_low'},
      '',
      '',
      ARRAY[]::text[],
      15,
      NOW(), NOW()
    )
  `);
}

// ── Main worker ──────────────────────────────────────────────────────────────

export async function startCurriculumAugmentor(): Promise<void> {
  console.log('[CurriculumAugmentor] Starting — scanning Level 3-5 paths for missing topic units...');

  const db = getSharedDb();

  const paths = await db.execute(sql`
    SELECT id, language, name, start_level
    FROM curriculum_paths
    WHERE start_level IN ('intermediate_low', 'intermediate_mid', 'advanced_low')
      AND is_published = true
    ORDER BY language, start_level
  `);

  let totalAdded = 0;
  let totalSkipped = 0;

  for (const pathRow of paths.rows as any[]) {
    const { id: pathId, language, name: pathName, start_level } = pathRow;
    const topicsForLevel = TOPICS_BY_LEVEL[start_level];
    if (!topicsForLevel) continue;

    const existingUnitNames = await getExistingUnits(pathId);
    let maxOrder = await getMaxUnitOrder(pathId);

    for (const topicDef of topicsForLevel) {
      // Check if a unit with this topic already exists (keyword match)
      const alreadyExists = existingUnitNames.some(name =>
        topicDef.keywords.some(kw => name.includes(kw.toLowerCase()))
      );

      if (alreadyExists) {
        console.log(`[CurriculumAugmentor] Skipping ${language}/${pathName} — "${topicDef.name}" already present`);
        totalSkipped++;
        continue;
      }

      console.log(`[CurriculumAugmentor] Generating "${topicDef.name}" for ${language} (${pathName})...`);

      const generated = await generateUnit(language, topicDef, start_level);
      if (!generated) {
        console.error(`[CurriculumAugmentor] Failed to generate "${topicDef.name}" for ${language}`);
        continue;
      }

      maxOrder++;
      const unitId = await insertUnit(pathId, topicDef, generated, maxOrder, start_level);
      await insertLessons(unitId, generated.lessons);

      console.log(`[CurriculumAugmentor] ✓ Added "${topicDef.name}" (${generated.lessons.length + 1} lessons) to ${language}/${pathName}`);
      totalAdded++;

      // Small yield between augmentor calls
      await new Promise(r => setTimeout(r, 100));
    }
  }

  console.log(`[CurriculumAugmentor] Complete — ${totalAdded} units added, ${totalSkipped} already existed`);
}
