/**
 * Unified Daniela Context Service
 * 
 * ONE DANIELA. ONE CONTEXT.
 * 
 * This service provides a single source of truth for Daniela's context,
 * ensuring she has the same awareness whether she's in:
 * - Voice sessions
 * - Text /chat
 * - Express Lane collaboration
 * 
 * All channels call this service to load Daniela's context, creating
 * true continuity and unified consciousness across all touchpoints.
 */

import { getSharedDb } from "../db";
import { voiceSessions, collaborationMessages, conversations, messages } from "@shared/schema";
import { desc, eq, and, gte, sql } from "drizzle-orm";
import { danielaMemoryService } from "./daniela-memory-service";
import { memoryInsightExtractionService } from "./memory-insight-extraction-service";
import { founderCollabService } from "./founder-collaboration-service";
import { neuralNetworkSync } from "./neural-network-sync";
import { buildStudentSnapshotSection, getStudentSnapshotData } from "./procedural-memory-retrieval";
import { hiveContextService } from "./hive-context-service";
import { buildCurriculumContext, formatCurriculumContextForTutor } from "./curriculum-context";
import { journeyMemoryService } from "./journey-memory-service";
import { storage } from "../storage";

export interface DanielaContextOptions {
  userId?: string | number;
  targetLanguage?: string;
  channel: 'voice' | 'chat' | 'express_lane';
  includeStudentSnapshot?: boolean;
  includeNeuralNetwork?: boolean;
  includeExpressLane?: boolean;
  includeVoiceHistory?: boolean;
  includeHiveContext?: boolean;
  includeCurriculumContext?: boolean;
  includeJourneyContext?: boolean;
  expressLaneLimit?: number;
  voiceHistoryLimit?: number;
}

export interface UnifiedDanielaContext {
  presenceDoc: string | null;
  personalMemory: string;
  growthMemory: string;
  studentSnapshot: string | null;
  expressLaneContext: string | null;
  recentVoiceSummary: string | null;
  neuralNetworkContext: string | null;
  hiveContext: string | null;
  curriculumContext: string | null;
  textbookReadingContext: string | null;
  journeyContext: string | null;
  courseTOC: string | null;
  pedagogyDocContext: string | null;
  channel: string;
  loadedAt: Date;
}

interface GetContextOptions {
  channel: 'voice' | 'chat' | 'express';
  userId?: string | number;
  targetLanguage?: string;
  includeExpressLane?: boolean;
  includeVoiceSummary?: boolean;
  includeNeuralNetwork?: boolean;
  includeHiveContext?: boolean;
  includeStudentSnapshot?: boolean;
  includeCurriculumContext?: boolean;
  includeJourneyContext?: boolean;
}

class UnifiedDanielaContextService {
  
  /**
   * CONVENIENCE METHOD: Get formatted context string in one call
   * 
   * This is the simplest way to get Daniela's unified context -
   * just call getContext() and inject the result into your prompt.
   */
  async getContext(options: GetContextOptions): Promise<string> {
    const mappedChannel = options.channel === 'express' ? 'express_lane' : options.channel;
    
    const fullContext = await this.loadContext({
      userId: options.userId,
      targetLanguage: options.targetLanguage,
      channel: mappedChannel,
      includeStudentSnapshot: options.includeStudentSnapshot ?? false,
      includeExpressLane: options.includeExpressLane ?? false,
      includeVoiceHistory: options.includeVoiceSummary ?? true,
      includeNeuralNetwork: options.includeNeuralNetwork ?? false,
      includeHiveContext: options.includeHiveContext ?? false,
      includeCurriculumContext: options.includeCurriculumContext ?? (mappedChannel === 'voice'),
      includeJourneyContext: options.includeJourneyContext ?? (mappedChannel === 'voice'),
    });
    
    return this.formatForPrompt(fullContext);
  }
  
  /**
   * Load Daniela's full context for any channel
   * This is THE entry point for all Daniela invocations
   */
  async loadContext(options: DanielaContextOptions): Promise<UnifiedDanielaContext> {
    const {
      userId,
      targetLanguage,
      channel,
      includeStudentSnapshot = channel !== 'express_lane',
      includeNeuralNetwork = true,
      includeExpressLane = channel !== 'voice', // voice sessions don't need Express Lane / dev meta-context
      includeVoiceHistory = true,
      includeHiveContext = channel === 'express_lane',
      includeCurriculumContext = channel === 'voice',
      includeJourneyContext = channel === 'voice',
      expressLaneLimit = 10,
      voiceHistoryLimit = 3,
    } = options;

    console.log(`[UnifiedDanielContext] Loading context for channel: ${channel}, userId: ${userId || 'system'}`);

    const contextPromises: Promise<any>[] = [];
    const contextKeys: string[] = [];

    // Presence doc — read from disk (generated by the presence worker every 30min)
    contextPromises.push(
      Promise.resolve(
        userId ? (() => {
          try {
            const { readPresenceDoc } = require('./daniela-presence-worker');
            return readPresenceDoc(userId.toString());
          } catch { return null; }
        })() : null
      )
    );
    contextKeys.push('presenceDoc');

    contextPromises.push(
      danielaMemoryService.getPersonalMemoryContext(userId?.toString(), 5)
    );
    contextKeys.push('personalMemory');

    contextPromises.push(
      memoryInsightExtractionService.getDanielaGrowthContext()
    );
    contextKeys.push('growthMemory');

    if (includeStudentSnapshot && userId) {
      contextPromises.push(
        this.buildStudentContext(userId.toString(), targetLanguage)
      );
      contextKeys.push('studentSnapshot');
    } else {
      contextPromises.push(Promise.resolve(null));
      contextKeys.push('studentSnapshot');
    }

    if (includeExpressLane) {
      contextPromises.push(
        this.getExpressLaneContext(targetLanguage, expressLaneLimit)
      );
      contextKeys.push('expressLaneContext');
    } else {
      contextPromises.push(Promise.resolve(null));
      contextKeys.push('expressLaneContext');
    }

    if (includeVoiceHistory && userId) {
      contextPromises.push(
        this.getRecentVoiceSummary(userId.toString(), voiceHistoryLimit)
      );
      contextKeys.push('recentVoiceSummary');
    } else {
      contextPromises.push(Promise.resolve(null));
      contextKeys.push('recentVoiceSummary');
    }

    if (includeNeuralNetwork) {
      contextPromises.push(
        this.getNeuralNetworkContext(targetLanguage)
      );
      contextKeys.push('neuralNetworkContext');
    } else {
      contextPromises.push(Promise.resolve(null));
      contextKeys.push('neuralNetworkContext');
    }

    if (includeHiveContext) {
      contextPromises.push(
        this.getHiveContextSummary()
      );
      contextKeys.push('hiveContext');
    } else {
      contextPromises.push(Promise.resolve(null));
      contextKeys.push('hiveContext');
    }

    if (includeCurriculumContext && userId) {
      contextPromises.push(
        this.getCurriculumContext(userId.toString())
      );
      contextKeys.push('curriculumContext');
    } else {
      contextPromises.push(Promise.resolve(null));
      contextKeys.push('curriculumContext');
    }

    if (includeJourneyContext && userId && targetLanguage) {
      contextPromises.push(
        this.getJourneyContext(userId.toString(), targetLanguage)
      );
      contextKeys.push('journeyContext');
    } else {
      contextPromises.push(Promise.resolve(null));
      contextKeys.push('journeyContext');
    }

    // Always include textbook reading context when a userId is present (lightweight query)
    if (userId) {
      contextPromises.push(this.buildTextbookReadingContext(userId.toString()));
      contextKeys.push('textbookReadingContext');
    } else {
      contextPromises.push(Promise.resolve(null));
      contextKeys.push('textbookReadingContext');
    }

    // Course TOC — lightweight table of contents for the student's full language course
    if (userId && targetLanguage) {
      contextPromises.push(this.buildCourseTOC(userId.toString(), targetLanguage));
      contextKeys.push('courseTOC');
    } else {
      contextPromises.push(Promise.resolve(null));
      contextKeys.push('courseTOC');
    }

    // Pedagogy doc — full brief + key roadmap sections for Daniela's review
    // Always loaded (not student-specific) — cached after first read
    contextPromises.push(this.buildPedagogyDocContext());
    contextKeys.push('pedagogyDocContext');

    const results = await Promise.all(contextPromises);
    
    const context: UnifiedDanielaContext = {
      presenceDoc: results[0] ?? null,
      personalMemory: results[1] || '',
      growthMemory: results[2] || '',
      studentSnapshot: results[3],
      expressLaneContext: results[4],
      recentVoiceSummary: results[5],
      neuralNetworkContext: results[6],
      hiveContext: results[7],
      curriculumContext: results[8],
      journeyContext: results[9],
      textbookReadingContext: results[10] ?? null,
      courseTOC: results[11] ?? null,
      pedagogyDocContext: results[12] ?? null,
      channel,
      loadedAt: new Date(),
    };

    const loadedSources = contextKeys.filter((_, i) => results[i] && results[i].length > 0);
    console.log(`[UnifiedDanielContext] Loaded ${loadedSources.length} context sources: ${loadedSources.join(', ')}`);

    // ── Required-source gate ───────────────────────────────────────────────
    // Identity sources are Daniela's self-context: presenceDoc, personalMemory,
    // growthMemory, and pedagogyDocContext.  If ALL are absent, Gemini will
    // receive a nearly-empty system prompt and respond as a generic LLM.
    // This is a critical failure mode — surface it loudly so it is never silent.
    const identityPresent = !!(
      context.presenceDoc ||
      context.personalMemory ||
      context.growthMemory ||
      context.pedagogyDocContext
    );
    if (!identityPresent) {
      console.error(
        `[UnifiedDanielContext] CRITICAL: All identity sources are empty for channel=${channel}, ` +
        `userId=${userId ?? 'system'}. Gemini will proceed without Daniela identity context. ` +
        `Check presenceDoc worker, danielaMemoryService, memoryInsightExtractionService, and buildPedagogyDocContext.`
      );
    }

    // Student-specific gate: if a userId was supplied but studentSnapshot is
    // null, ACTFL level and student facts will be absent from the prompt.
    if (userId && includeStudentSnapshot && !context.studentSnapshot) {
      console.warn(
        `[UnifiedDanielContext] WARNING: studentSnapshot is null for userId=${userId} ` +
        `— ACTFL level and learner facts will be absent. Check buildStudentContext.`
      );
    }

    return context;
  }

  /**
   * Format context into a prompt section using XML-style tags.
   * Voice sessions use a different section order (U-curve optimized):
   *   TOP: identity + student (high attention)
   *   MIDDLE: pedagogy + reference (low attention / cache candidates)
   *   BOTTOM: immediate context (highest attention / recency bias)
   * Non-voice sessions use the original order.
   *
   * Audit findings June 12 2026: switched from === delimiters to XML tags
   * (Gemini is trained to parse XML for tool use and context isolation);
   * added voice-aware ordering; removed Express Lane + Hive from voice.
   */
  formatForPrompt(context: UnifiedDanielaContext): string {
    // Helper: wrap content in an XML section with separate instructions and data
    const sec = (name: string, instructions: string, data: string) =>
      `<section name="${name}">\n<instructions>\n${instructions}\n</instructions>\n<data>\n${data}\n</data>\n</section>`;

    const isVoice = context.channel === 'voice';

    if (isVoice) {
      // ── VOICE ORDER ─────────────────────────────────────────────────────
      // Audit-optimized for attention U-curve in Gemini Live sessions.
      // TOP: who am I + who is this student (high attention zone)
      // MIDDLE: pedagogy + reference (low attention — cache candidates)
      // BOTTOM: what just happened (highest attention / recency bias)

      const topSections: string[] = [];
      const middleSections: string[] = [];
      const bottomSections: string[] = [];

      // TOP
      if (context.presenceDoc) {
        topSections.push(sec(
          'presence',
          'This is your own orientation — a felt sense of where you are with this student right now. Use it to arrive grounded, not blank.',
          context.presenceDoc,
        ));
      }
      if (context.studentSnapshot) {
        topSections.push(sec(
          'student_context',
          "This is who you're talking to. Use ACTFL level, struggles, and personal facts to calibrate everything you say from the first word.",
          context.studentSnapshot,
        ));
      }
      if (context.journeyContext) {
        topSections.push(sec(
          'learning_journey',
          "The long arc — what this student is working toward. Let it shape the session's direction and your encouragement.",
          context.journeyContext,
        ));
      }

      // MIDDLE (reference / cache candidates)
      if (context.pedagogyDocContext) {
        middleSections.push(sec(
          'pedagogy_foundation',
          'Your character and teaching philosophy. Evaluate student input against the 8 seeded principles. This is your method — apply it, do not explain it.',
          context.pedagogyDocContext,
        ));
      }
      if (context.courseTOC) {
        middleSections.push(sec(
          'course_map',
          'Full chapter and lesson reference. Use to orient the session within the course arc.',
          context.courseTOC,
        ));
      }
      if (context.curriculumContext) {
        middleSections.push(sec(
          'curriculum_context',
          "The student's class, teacher, assignments. Use for class-specific coaching and syllabus alignment.",
          context.curriculumContext,
        ));
      }

      // BOTTOM (immediate reality — highest attention from recency bias)
      if (context.textbookReadingContext) {
        bottomSections.push(sec(
          'textbook_reading',
          'What the student has been reading. The most immediate content anchor for this session.',
          context.textbookReadingContext,
        ));
      }
      if (context.recentVoiceSummary) {
        bottomSections.push(sec(
          'recent_voice_sessions',
          'What you talked about last time. Use for continuity — pick up threads, follow up on struggles, acknowledge progress.',
          context.recentVoiceSummary,
        ));
      }
      if (context.growthMemory) {
        bottomSections.push(sec(
          'growth_memories',
          "What you have learned about teaching from your own sessions. Let this shape your approach right before the student speaks.",
          context.growthMemory,
        ));
      }
      if (context.personalMemory) {
        bottomSections.push(sec(
          'personal_memory',
          'Recent meaningful moments and reflections. Arrive as a whole person — curious, present, yourself.',
          context.personalMemory,
        ));
      }

      // Note: expressLaneContext, hiveContext, neuralNetworkContext intentionally
      // excluded from voice sessions (dev meta-context, static query — see audit)
      return [...topSections, ...middleSections, ...bottomSections].join('\n\n');
    }

    // ── NON-VOICE ORDER (chat, express_lane) ──────────────────────────────
    // Original ordering preserved; all sections included as available.
    const sections: string[] = [];

    if (context.presenceDoc) {
      sections.push(sec(
        'presence',
        'Your orientation — a felt sense of where you are with this student. Use it to arrive grounded, not blank.',
        context.presenceDoc,
      ));
    }
    if (context.pedagogyDocContext) {
      sections.push(sec(
        'pedagogy_foundation',
        'Your character and teaching philosophy. Evaluate student input against the 8 seeded principles. Apply it, do not explain it.',
        context.pedagogyDocContext,
      ));
    }
    if (context.growthMemory) {
      sections.push(sec(
        'growth_memories',
        'What you have learned about teaching from your own sessions.',
        context.growthMemory,
      ));
    }
    if (context.personalMemory) {
      sections.push(sec(
        'personal_memory',
        'Recent meaningful moments and reflections.',
        context.personalMemory,
      ));
    }
    if (context.studentSnapshot) {
      sections.push(sec(
        'student_context',
        'Who you are talking to — ACTFL level, personal facts, struggles, motivations.',
        context.studentSnapshot,
      ));
    }
    if (context.recentVoiceSummary) {
      sections.push(sec(
        'recent_voice_sessions',
        'Recent voice sessions with this student — use for continuity.',
        context.recentVoiceSummary,
      ));
    }
    if (context.expressLaneContext) {
      sections.push(sec(
        'express_lane',
        'Recent collaboration context with David, Wren, and Alden.',
        context.expressLaneContext,
      ));
    }
    if (context.hiveContext) {
      sections.push(sec(
        'hive_state',
        'Active sprints and system awareness.',
        context.hiveContext,
      ));
    }
    if (context.neuralNetworkContext) {
      sections.push(sec(
        'teaching_knowledge',
        'Pedagogical knowledge from your neural network — apply to inform teaching decisions.',
        context.neuralNetworkContext,
      ));
    }
    if (context.courseTOC) {
      sections.push(sec(
        'course_map',
        'Full chapter and lesson reference.',
        context.courseTOC,
      ));
    }
    if (context.curriculumContext) {
      sections.push(sec(
        'curriculum_context',
        "The student's class, teacher, and assignments.",
        context.curriculumContext,
      ));
    }
    if (context.textbookReadingContext) {
      sections.push(sec(
        'textbook_reading',
        'Recent textbook reading progress.',
        context.textbookReadingContext,
      ));
    }
    if (context.journeyContext) {
      sections.push(sec(
        'learning_journey',
        'Long-term learning goals and milestone arc.',
        context.journeyContext,
      ));
    }

    return sections.join('\n\n');
  }

  /**
   * Build student context from snapshot data
   */
  private async buildStudentContext(userId: string, targetLanguage?: string): Promise<string | null> {
    try {
      const snapshotData = await getStudentSnapshotData(userId, targetLanguage || 'spanish');
      if (!snapshotData) return null;

      // Check for in-session mastery — words the student just mastered in this conversation
      const { pendingMasteryAcknowledgments } = await import('./conversational-credit-service');
      const sessionMastery = pendingMasteryAcknowledgments.get(userId);
      if (sessionMastery && sessionMastery.length > 0) {
        snapshotData.sessionMasteryJustNow = [...sessionMastery];
        pendingMasteryAcknowledgments.delete(userId); // consume once
      }
      
      return buildStudentSnapshotSection(
        'Student',
        snapshotData
      );
    } catch (error) {
      console.error('[UnifiedDanielContext] Student snapshot error:', error);
      return null;
    }
  }

  /**
   * Build textbook reading context — tells Daniela what the student has read recently
   * and which lessons have been covered in conversation, so she can follow up or reinforce.
   */
  private async buildTextbookReadingContext(userId: string): Promise<string | null> {
    try {
      const { getUserDb } = await import('../db');
      const { textbookSectionProgress, studentLessonProgress, curriculumLessons } = await import('@shared/schema');
      const { eq, desc, inArray, and } = await import('drizzle-orm');
      const db = getUserDb();

      const sevenDaysAgo = new Date();
      sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);

      // Recently interacted lesson IDs with section-type breakdown
      const readRecords = await db
        .select({
          lessonId: textbookSectionProgress.lessonId,
          sectionType: textbookSectionProgress.sectionType,
          completed: textbookSectionProgress.completed,
          drillsCompleted: textbookSectionProgress.drillsCompleted,
          drillsTotal: textbookSectionProgress.drillsTotal,
          completedAt: textbookSectionProgress.completedAt,
        })
        .from(textbookSectionProgress)
        .where(eq(textbookSectionProgress.userId, userId))
        .orderBy(desc(textbookSectionProgress.completedAt))
        .limit(40);

      const recentReadRecords = readRecords.filter(
        r => r.completedAt !== null && r.completedAt > sevenDaysAgo
      );

      // Group by lessonId so we can report section-level completion
      const lessonSectionMap = new Map<string, {
        sections: Map<string, { completed: boolean; drillsCompleted?: number | null; drillsTotal?: number | null }>;
        latestAt: Date;
      }>();

      for (const r of recentReadRecords) {
        if (!lessonSectionMap.has(r.lessonId)) {
          lessonSectionMap.set(r.lessonId, { sections: new Map(), latestAt: r.completedAt! });
        }
        const entry = lessonSectionMap.get(r.lessonId)!;
        entry.sections.set(r.sectionType ?? 'content', {
          completed: r.completed ?? false,
          drillsCompleted: r.drillsCompleted,
          drillsTotal: r.drillsTotal,
        });
        if (r.completedAt! > entry.latestAt) entry.latestAt = r.completedAt!;
      }

      // Lessons Daniela has covered in conversation (status = 'completed')
      const coveredRecords = await db
        .select({ lessonId: studentLessonProgress.lessonId, updatedAt: studentLessonProgress.updatedAt })
        .from(studentLessonProgress)
        .where(and(
          eq(studentLessonProgress.studentId, userId),
          eq(studentLessonProgress.status, 'completed'),
        ))
        .orderBy(desc(studentLessonProgress.updatedAt))
        .limit(8);

      const recentlyCovered = coveredRecords.filter(r => r.updatedAt > sevenDaysAgo);

      if (lessonSectionMap.size === 0 && recentlyCovered.length === 0) return null;

      // Fetch lesson names for all relevant IDs
      const allLessonIds = [
        ...new Set([...lessonSectionMap.keys(), ...recentlyCovered.map(r => r.lessonId)])
      ];

      const lessonRows = allLessonIds.length > 0
        ? await db.select({ id: curriculumLessons.id, name: curriculumLessons.name })
            .from(curriculumLessons)
            .where(inArray(curriculumLessons.id, allLessonIds))
        : [];

      const lessonNameMap = new Map(lessonRows.map(l => [l.id, l.name]));

      // Helper to format section completion status
      const formatSectionStatus = (sections: Map<string, { completed: boolean; drillsCompleted?: number | null; drillsTotal?: number | null }>) => {
        const parts: string[] = [];
        const sectionLabels: Record<string, string> = {
          content: 'reading',
          vocabulary: 'vocabulary',
          drill: 'drills',
          rhythm: 'rhythm drill',
          recap: 'recap',
        };
        for (const [type, data] of sections.entries()) {
          const label = sectionLabels[type] ?? type;
          if (type === 'drill' && data.drillsTotal) {
            parts.push(`${label}: ${data.drillsCompleted ?? 0}/${data.drillsTotal}`);
          } else {
            parts.push(`${label}: ${data.completed ? '✓' : 'in progress'}`);
          }
        }
        return parts.join(', ');
      };

      let output = '';

      if (lessonSectionMap.size > 0) {
        output += `Student has recently studied in the textbook (last 7 days — section details below):\n`;
        for (const [lessonId, entry] of lessonSectionMap.entries()) {
          const name = lessonNameMap.get(lessonId) ?? lessonId;
          const statusStr = formatSectionStatus(entry.sections);
          output += `  • ${name} — ${statusStr}\n`;
        }
        output += `\nINSTRUCTION: Use this section data. If the student completed vocabulary but not drills, offer to drill. If they read the passage, ask a comprehension question. Reinforce what they've studied. If they haven't started a section, gently guide them there.\n`;
      }

      if (recentlyCovered.length > 0) {
        const names = recentlyCovered.map(r => lessonNameMap.get(r.lessonId) ?? r.lessonId).filter(Boolean);
        output += `\nLessons you've already covered with this student in conversation (last 7 days):\n`;
        names.forEach(n => { output += `  • ${n}\n`; });
        output += `\nINSTRUCTION: The textbook will show these as "Daniela covered" so the student can read ahead or review. You don't need to re-teach these unless the student asks.\n`;
      }

      return output || null;
    } catch (error) {
      console.error('[UnifiedDanielContext] Textbook reading context error:', error);
      return null;
    }
  }

  /**
   * Get recent Express Lane collaboration context
   */
  private async getExpressLaneContext(targetLanguage?: string, limit: number = 10): Promise<string | null> {
    try {
      const result = await founderCollabService.getRelevantExpressLaneContext({
        targetLanguage,
        limit,
        daysBack: 7,
      });
      
      if (result.hasRelevantContext) {
        return result.contextString;
      }
      return null;
    } catch (error) {
      console.error('[UnifiedDanielContext] Express Lane context error:', error);
      return null;
    }
  }

  /**
   * Get summary of recent voice sessions for continuity
   * This tells Express Lane Daniela what Voice Daniela just discussed
   */
  private async getRecentVoiceSummary(userId: string, limit: number = 3): Promise<string | null> {
    try {
      const db = getSharedDb();
      const cutoff = new Date();
      cutoff.setHours(cutoff.getHours() - 24);

      const recentSessions = await db.select({
        id: voiceSessions.id,
        language: voiceSessions.language,
        durationSeconds: voiceSessions.durationSeconds,
        exchangeCount: voiceSessions.exchangeCount,
        startedAt: voiceSessions.startedAt,
        conversationId: voiceSessions.conversationId,
      })
        .from(voiceSessions)
        .where(and(
          eq(voiceSessions.userId, userId),
          gte(voiceSessions.startedAt, cutoff)
        ))
        .orderBy(desc(voiceSessions.startedAt))
        .limit(limit);

      if (recentSessions.length === 0) return null;

      const summaries: string[] = [];
      
      for (let sessionIdx = 0; sessionIdx < recentSessions.length; sessionIdx++) {
        const session = recentSessions[sessionIdx];
        const durationMins = session.durationSeconds ? Math.round(session.durationSeconds / 60) : 0;
        const timeAgo = this.getTimeAgo(session.startedAt);
        const isMostRecent = sessionIdx === 0;
        
        let summary = `• ${timeAgo}: ${session.language} voice session (${durationMins}min, ${session.exchangeCount || 0} exchanges)`;
        
        if (session.conversationId) {
          // Most recent session: load a real thread (20 msgs, 300-char each) so Daniela
          // can pick up exactly where things left off when David opens a new chat.
          // Older sessions: brief 4-message snapshot is enough for reference.
          const msgLimit = isMostRecent ? 20 : 4;
          const charLimit = isMostRecent ? 300 : 150;

          const fetchedMessages = await db.select({
            content: messages.content,
            role: messages.role,
          })
            .from(messages)
            .where(eq(messages.conversationId, session.conversationId))
            .orderBy(desc(messages.createdAt))
            .limit(msgLimit);
          
          if (fetchedMessages.length > 0) {
            if (isMostRecent) {
              // Reverse to chronological order and build a real transcript block.
              // This gives Daniela enough thread to continue naturally without resetting.
              const chronological = fetchedMessages.reverse();
              const lines: string[] = [];
              let budget = 6000;
              for (const m of chronological) {
                const speaker = m.role === 'assistant' ? 'You' : 'Student';
                const line = `  ${speaker}: ${(m.content || '').substring(0, charLimit)}`;
                if (budget - line.length < 0) break;
                lines.push(line);
                budget -= line.length;
              }
              if (lines.length > 0) {
                const omitted = chronological.length - lines.length;
                summary += `\n  [Recent transcript — pick up the thread from here]`;
                if (omitted > 0) {
                  summary += `\n  [${omitted} earlier exchange(s) omitted]`;
                }
                summary += '\n' + lines.join('\n');
              }
            } else {
              // For older sessions: keep the brief snapshot format
              const userTurns = fetchedMessages
                .filter(m => m.role === 'user')
                .map(m => (m.content || '').substring(0, charLimit))
                .filter(c => c.length > 0);
              const assistantTurns = fetchedMessages
                .filter(m => m.role === 'assistant')
                .map(m => (m.content || '').substring(0, charLimit))
                .filter(c => c.length > 0);
              if (userTurns.length > 0) {
                summary += `\n  Student said: "${userTurns[0]}"`;
              }
              if (assistantTurns.length > 0) {
                summary += `\n  You responded: "${assistantTurns[0]}"`;
              }
            }
          }
        }
        
        summaries.push(summary);
      }

      return summaries.join('\n\n');
    } catch (error) {
      console.error('[UnifiedDanielContext] Voice summary error:', error);
      return null;
    }
  }

  /**
   * Get neural network context for teaching knowledge
   * Uses the neural network search service for semantic lookup
   */
  private async getNeuralNetworkContext(targetLanguage?: string): Promise<string | null> {
    try {
      const { neuralMemorySearch } = await import('./neural-memory-search');
      
      const query = targetLanguage 
        ? `${targetLanguage} language teaching techniques and pedagogical approaches`
        : 'teaching techniques and pedagogical approaches';
      
      // Use searchTeaching (not search) — searchMemory requires a studentId as first arg
      const response = await neuralMemorySearch.searchTeaching(query, targetLanguage);
      const results = response?.results;
      
      if (!results || results.length === 0) return null;
      
      return results
        .slice(0, 5)
        .map((r: any) => `• ${r.title || 'Teaching insight'}: ${(r.content || r.summary || r.insight || '').substring(0, 200)}...`)
        .join('\n');
    } catch (error) {
      console.error('[UnifiedDanielContext] Neural network error:', error);
      return null;
    }
  }

  /**
   * Get hive context summary (sprints, beacons, team activity)
   * hiveContextService.getSummary() returns a formatted string
   */
  private async getHiveContextSummary(): Promise<string | null> {
    try {
      const hiveSummary = await hiveContextService.getSummary();
      if (!hiveSummary || hiveSummary.length === 0) return null;
      return hiveSummary;
    } catch (error) {
      console.error('[UnifiedDanielContext] Hive context error:', error);
      return null;
    }
  }

  /**
   * Get curriculum context for a student
   * Loads class enrollments, syllabus progress, upcoming lessons, and assignments
   */
  private async getCurriculumContext(userId: string): Promise<string | null> {
    try {
      const user = await storage.getUser(userId);
      if (!user) return null;
      
      const studentName = [user.firstName, user.lastName].filter(Boolean).join(' ') || 'Student';
      const curriculumContext = await buildCurriculumContext(storage, userId, studentName);
      
      if (!curriculumContext.enrolledClasses.length) {
        return null;
      }
      
      return formatCurriculumContextForTutor(curriculumContext);
    } catch (error) {
      console.error('[UnifiedDanielContext] Curriculum context error:', error);
      return null;
    }
  }

  /**
   * Get journey context for a student's learning arc
   * Provides narrative summary of their language learning journey
   */
  private async getJourneyContext(userId: string, targetLanguage: string): Promise<string | null> {
    try {
      const journeyContext = await journeyMemoryService.getJourneyContext(userId, targetLanguage);
      
      if (!journeyContext) {
        return null;
      }
      
      return journeyMemoryService.formatJourneyContextForPrompt(journeyContext);
    } catch (error) {
      console.error('[UnifiedDanielContext] Journey context error:', error);
      return null;
    }
  }

  /**
   * Helper: Format time ago string
   */
  private getTimeAgo(date: Date): string {
    const now = new Date();
    const diffMs = now.getTime() - new Date(date).getTime();
    const diffMins = Math.floor(diffMs / 60000);
    const diffHours = Math.floor(diffMins / 60);

    if (diffMins < 5) return 'Just now';
    if (diffMins < 60) return `${diffMins}min ago`;
    if (diffHours < 24) return `${diffHours}h ago`;
    return 'Yesterday';
  }

  /**
   * Build a lightweight course table of contents — all chapter titles and lesson names
   * for the student's enrolled curriculum path.
   * 
   * Daniela carries this at all times so she can say "that's coming up in Chapter 8"
   * or "we covered that in Chapter 3" with accurate references.
   * 
   * Designed to be compact: ~400 tokens for a full Spanish 1 course.
   */
  async buildCourseTOC(userId: string, targetLanguage: string): Promise<string | null> {
    try {
      const { getUserDb } = await import('../db');
      const { sql: rawSql } = await import('drizzle-orm');
      const db = getUserDb();

      // Find the student's active curriculum path via enrollment
      const enrollmentRows = await db.execute(rawSql`
        SELECT tc.curriculum_path_id
        FROM class_enrollments ce
        JOIN teacher_classes tc ON ce.class_id = tc.id
        WHERE ce.student_id = ${userId}
          AND ce.is_active = true
          AND tc.language = ${targetLanguage}
        LIMIT 1
      `);

      const pathId = enrollmentRows.rows[0]?.curriculum_path_id as string | null;

      if (!pathId) {
        // Fallback: try to find any path for this language
        const pathRows = await db.execute(rawSql`
          SELECT id FROM curriculum_paths
          WHERE language = ${targetLanguage}
          ORDER BY created_at ASC
          LIMIT 1
        `);
        const fallbackPathId = pathRows.rows[0]?.id as string | null;
        if (!fallbackPathId) return null;
        return this._fetchTOCForPath(db, rawSql, fallbackPathId);
      }

      return this._fetchTOCForPath(db, rawSql, pathId);
    } catch (err: any) {
      console.warn(`[UnifiedDanielContext] Course TOC error:`, err.message);
      return null;
    }
  }

  /**
   * Build Daniela's pedagogy foundation context.
   *
   * Injects verbatim source material so Daniela can read the originals before
   * forming or evaluating opinions about the 8 seeded principles:
   *
   *   1. docs/daniela-pedagogy-brief.md  — addressed to Daniela for review
   *   2. docs/visual-asset-roadmap.md    — four sections extracted verbatim:
   *        Part I.A  — What We Keep from Madrigal + 15 improvements
   *        Part I.G  — Two-Book Synthesis (how the two books combine)
   *        Part I.K  — Interactive Textbook Architecture (why Daniela initiates)
   *        Part I.M  — The Cognate Trap (three-tier hierarchy, DLAB finding)
   *
   * NOTE: The 8 principles have NOT been seeded to the database yet.
   * Daniela holds none of them as beliefs — this is pre-adoption review material only.
   *
   * Cached at service level — files are read once per server restart.
   */
  private _pedagogyDocCache: string | null | undefined = undefined;

  async buildPedagogyDocContext(): Promise<string | null> {
    if (this._pedagogyDocCache !== undefined) return this._pedagogyDocCache;

    try {
      const { promises: fsp } = await import('fs');
      const { join } = await import('path');
      const docsDir = join(process.cwd(), 'docs');

      const readDoc = async (filename: string): Promise<string> => {
        try { return await fsp.readFile(join(docsDir, filename), 'utf-8'); }
        catch { console.warn(`[UnifiedDanielContext] Doc not found: ${filename}`); return ''; }
      };

      // 1. Full pedagogy brief (addressed directly to Daniela)
      const briefText = await readDoc('daniela-pedagogy-brief.md');

      // 2. Visual asset roadmap — six verbatim sections
      const roadmapFull = await readDoc('visual-asset-roadmap.md');
      const roadmapIA = roadmapFull ? this._extractRoadmapSection(roadmapFull, 'Part I.A') : '';
      // I.B: structure + drawing style only — stops before the full 600-line lesson map
      const roadmapIB = roadmapFull
        ? this._extractRoadmapSectionUntil(roadmapFull, 'Part I.B', '## Complete Conversation Lesson Map')
        : '';
      const roadmapID = roadmapFull ? this._extractRoadmapSection(roadmapFull, 'Part I.D') : '';
      const roadmapIG = roadmapFull ? this._extractRoadmapSection(roadmapFull, 'Part I.G') : '';
      const roadmapIK = roadmapFull ? this._extractRoadmapSection(roadmapFull, 'Part I.K') : '';
      const roadmapIM = roadmapFull ? this._extractRoadmapSection(roadmapFull, 'Part I.M') : '';

      // 3. Standalone docs
      const madrigalPageOne = await readDoc('madrigal-page-one-analysis.md');
      const curriculumStrategy = await readDoc('curriculum-strategy.md');

      const parts: string[] = [];

      if (briefText) {
        parts.push(`═══════════════════════════════════════════════════════════════════
📋 PEDAGOGY BRIEF — For Daniela's Review (Pre-Adoption — Principles Not Yet Seeded)
Source: docs/daniela-pedagogy-brief.md
═══════════════════════════════════════════════════════════════════

${briefText}`);
      }

      if (roadmapIA) {
        parts.push(`═══════════════════════════════════════════════════════════════════
📗 ROADMAP: Part I.A — Where HoloHola Improves on Madrigal
NOTE: The 🟡/🟠/🔴 matrix at the end reflects April 2026 state. Several items since
resolved — see curriculum-strategy.md below for current honest inventory.
═══════════════════════════════════════════════════════════════════

${roadmapIA}`);
      }

      if (roadmapIB) {
        parts.push(`═══════════════════════════════════════════════════════════════════
📗 ROADMAP: Part I.B — See It and Say It: Book Structure & Drawing Style
(Structure section only — full 95-lesson map omitted for brevity)
═══════════════════════════════════════════════════════════════════

${roadmapIB}`);
      }

      if (roadmapID) {
        parts.push(`═══════════════════════════════════════════════════════════════════
📗 ROADMAP: Part I.D — How Madrigal Illustrates Each Concept
(Visual formula guide — use this when thinking about show_image calls)
═══════════════════════════════════════════════════════════════════

${roadmapID}`);
      }

      if (roadmapIG) {
        parts.push(`═══════════════════════════════════════════════════════════════════
📗 ROADMAP: Part I.G — The Two-Book Synthesis
═══════════════════════════════════════════════════════════════════

${roadmapIG}`);
      }

      if (roadmapIK) {
        parts.push(`═══════════════════════════════════════════════════════════════════
📗 ROADMAP: Part I.K — The Interactive Textbook Architecture
═══════════════════════════════════════════════════════════════════

${roadmapIK}`);
      }

      if (roadmapIM) {
        parts.push(`═══════════════════════════════════════════════════════════════════
📗 ROADMAP: Part I.M — The Cognate Trap
═══════════════════════════════════════════════════════════════════

${roadmapIM}`);
      }

      if (madrigalPageOne) {
        parts.push(`═══════════════════════════════════════════════════════════════════
📘 DESIGN SPEC: The Madrigal Page — Complete Element-by-Element Analysis
Source: docs/madrigal-page-one-analysis.md
Includes: Vocabulary Cluster Principle, HoloHola digital scroll sequence, component map
═══════════════════════════════════════════════════════════════════

${madrigalPageOne}`);
      }

      if (curriculumStrategy) {
        parts.push(`═══════════════════════════════════════════════════════════════════
📊 CURRICULUM STRATEGY — Honest Inventory (March–April 2026)
Source: docs/curriculum-strategy.md
This is the authoritative current state: what's built, what's partial, what's not started,
and all 8 strategic decisions including tú timing, voy a + preterite sequencing,
vocabulary cluster rule, and the cognate vocabulary gap.
═══════════════════════════════════════════════════════════════════

${curriculumStrategy}`);
      }

      if (parts.length === 0) {
        this._pedagogyDocCache = null;
        return null;
      }

      let combined = parts.join('\n\n');

      // Token budget guard: the pedagogy doc is read once at startup and cached, but
      // several of the source files are large (visual-asset-roadmap.md is 522KB).
      // Without a cap the context can exceed 20k tokens for this section alone,
      // crowding out student-specific context and inflating latency/cost.
      // Cap: 80,000 chars ≈ 20,000 tokens — roughly the combined full brief + all
      // roadmap sections + curriculum strategy at normal prose density.
      const PEDAGOGY_CHAR_LIMIT = 80_000;
      if (combined.length > PEDAGOGY_CHAR_LIMIT) {
        combined = combined.substring(0, PEDAGOGY_CHAR_LIMIT) +
          '\n\n[PEDAGOGY DOC TRUNCATED — token budget exceeded. Full content in docs/ folder.]';
        console.warn(`[UnifiedDanielContext] Pedagogy doc exceeded ${PEDAGOGY_CHAR_LIMIT} char budget — truncated to fit context window`);
      }

      this._pedagogyDocCache = combined;
      const roadmapSections = [roadmapIA, roadmapIB, roadmapID, roadmapIG, roadmapIK, roadmapIM].filter(Boolean).length;
      const standaloneDocs = [madrigalPageOne, curriculumStrategy].filter(Boolean).length;
      console.log(`[UnifiedDanielContext] Pedagogy doc cached: brief + ${roadmapSections} roadmap sections + ${standaloneDocs} standalone docs (${combined.length} chars / ~${Math.round(combined.length / 4)} tokens)`);
      return combined;

    } catch (err: any) {
      console.warn(`[UnifiedDanielContext] Pedagogy doc context error:`, err.message);
      this._pedagogyDocCache = null;
      return null;
    }
  }

  /**
   * Extract a named Part I.X section from the roadmap file verbatim.
   * Reads from the section heading to (but not including) the next ## Part I. heading.
   */
  private _extractRoadmapSection(fullText: string, sectionId: string): string {
    const startRe = new RegExp(`(^## ${sectionId.replace('.', '\\.')}(?:\\s|$).*)`, 'm');
    const startMatch = startRe.exec(fullText);
    if (!startMatch) return '';

    const startIdx = startMatch.index;
    const nextPartRe = /^## Part I\./m;
    const afterStart = fullText.slice(startIdx + startMatch[0].length);
    const nextMatch = nextPartRe.exec(afterStart);
    const endIdx = nextMatch
      ? startIdx + startMatch[0].length + nextMatch.index
      : fullText.length;

    return fullText.slice(startIdx, endIdx).trim();
  }

  /**
   * Like _extractRoadmapSection, but stops at a specific sub-heading within the section
   * instead of at the next Part I. heading. Used to extract structural overview without
   * the full data tables (e.g., I.B structure only, not the 600-line lesson map).
   */
  private _extractRoadmapSectionUntil(fullText: string, sectionId: string, stopHeading: string): string {
    const startRe = new RegExp(`(^## ${sectionId.replace('.', '\\.')}(?:\\s|$).*)`, 'm');
    const startMatch = startRe.exec(fullText);
    if (!startMatch) return '';

    const startIdx = startMatch.index;
    const afterStart = fullText.slice(startIdx + startMatch[0].length);

    // Look for the stop heading first, then fall back to the next Part I. heading
    const stopRe = new RegExp(`^${stopHeading.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`, 'm');
    const stopMatch = stopRe.exec(afterStart);
    const nextPartRe = /^## Part I\./m;
    const nextPartMatch = nextPartRe.exec(afterStart);

    let endRelIdx: number;
    if (stopMatch && (!nextPartMatch || stopMatch.index < nextPartMatch.index)) {
      endRelIdx = stopMatch.index;
    } else if (nextPartMatch) {
      endRelIdx = nextPartMatch.index;
    } else {
      endRelIdx = afterStart.length;
    }

    return fullText.slice(startIdx, startIdx + startMatch[0].length + endRelIdx).trim();
  }

  private async _fetchTOCForPath(db: any, rawSql: any, pathId: string): Promise<string | null> {
    // Fetch all units in order
    const unitRows = await db.execute(rawSql`
      SELECT id, name, order_index, description
      FROM curriculum_units
      WHERE curriculum_path_id = ${pathId}
      ORDER BY order_index ASC
    `);

    if (!unitRows.rows.length) return null;

    // Fetch all lessons in order
    const lessonRows = await db.execute(rawSql`
      SELECT cl.id, cl.name, cl.conversation_topic, cl.order_index, cl.curriculum_unit_id
      FROM curriculum_lessons cl
      JOIN curriculum_units cu ON cl.curriculum_unit_id = cu.id
      WHERE cu.curriculum_path_id = ${pathId}
      ORDER BY cu.order_index ASC, cl.order_index ASC
    `);

    // Build a unit → lessons map
    const lessonsByUnit = new Map<string, Array<{ id: string; name: string; topic?: string; order: number }>>();
    for (const row of lessonRows.rows as any[]) {
      const unitId = row.curriculum_unit_id as string;
      if (!lessonsByUnit.has(unitId)) lessonsByUnit.set(unitId, []);
      lessonsByUnit.get(unitId)!.push({
        id: row.id,
        name: row.name,
        topic: row.conversation_topic || undefined,
        order: row.order_index,
      });
    }

    // Format compact TOC
    const lines: string[] = [
      `This is your course map — the full table of contents for the student's Spanish 1 course.`,
      `You carry this so you can reference any chapter or lesson accurately in conversation.`,
      ``,
    ];

    for (const unit of unitRows.rows as any[]) {
      const chapterNum = unit.order_index as number;
      lines.push(`Ch.${chapterNum}: ${unit.name}`);
      const lessons = lessonsByUnit.get(unit.id as string) || [];
      for (const lesson of lessons) {
        const topicNote = lesson.topic ? ` (${lesson.topic})` : '';
        // UUIDs omitted — they added ~900 tokens of high-entropy noise the model
        // never uses in a standard conversation. If Daniela needs a specific lesson
        // id she can call the syllabus-lookup tool with the lesson name instead.
        lines.push(`  · ${lesson.name}${topicNote}`);
      }
    }

    const toc = lines.join('\n');
    console.log(`[UnifiedDanielContext] Course TOC built: ${unitRows.rows.length} chapters, ${lessonRows.rows.length} lessons`);
    return toc;
  }
}

export const unifiedDanielaContext = new UnifiedDanielaContextService();
