import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Checkbox } from "@/components/ui/checkbox";

export function TermsGate({ children }: { children: React.ReactNode }) {
  const [accepted, setAccepted] = useState(false);

  const acceptMutation = useMutation({
    mutationFn: () => apiRequest("POST", "/api/auth/accept-terms"),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/auth/user"] });
    },
  });

  return (
    <div
      className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4"
      data-testid="terms-gate-overlay"
    >
      <div className="bg-background rounded-md border shadow-lg w-full max-w-lg flex flex-col gap-4 p-6">
        <div>
          <h2 className="text-xl font-semibold">Terms of Service &amp; Privacy Policy</h2>
          <p className="text-sm text-muted-foreground mt-1">
            Please review and accept our terms before continuing.
          </p>
        </div>

        <ScrollArea className="h-60 rounded-md border p-4 text-sm text-foreground leading-relaxed" data-testid="terms-scroll-area">
          <p className="font-semibold mb-2">HolaHola AI — Terms of Service (Beta)</p>
          <p className="mb-2">
            By using HolaHola AI you agree to these terms. This is a beta product and features may change.
          </p>
          <p className="font-semibold mb-1">1. Use of Service</p>
          <p className="mb-2">
            HolaHola AI provides AI-powered Spanish and English language tutoring. You must be 13 years or older to use the service. You agree not to misuse the platform or attempt to circumvent its systems.
          </p>
          <p className="font-semibold mb-1">2. Billing &amp; Credits</p>
          <p className="mb-2">
            Paid plans and hour packages are charged in advance. Credits are consumed per minute of voice session time. Refunds are not available for consumed credits. Unused credits expire 12 months after purchase.
          </p>
          <p className="font-semibold mb-1">3. Privacy</p>
          <p className="mb-2">
            We collect conversation transcripts and usage data to improve your learning experience. Voice audio is not stored beyond the duration of your session. You may request deletion of your account and associated data at any time by contacting support.
          </p>
          <p className="font-semibold mb-1">4. AI-Generated Content</p>
          <p className="mb-2">
            Responses are generated by AI and may occasionally be inaccurate. Do not rely on this service for critical or safety-related information.
          </p>
          <p className="font-semibold mb-1">5. Changes to Terms</p>
          <p className="mb-2">
            We may update these terms from time to time. Continued use of the service after changes constitutes acceptance of the new terms.
          </p>
          <p className="text-muted-foreground text-xs mt-4">Last updated: April 2026</p>
        </ScrollArea>

        <label className="flex items-start gap-3 cursor-pointer" htmlFor="tos-checkbox">
          <Checkbox
            id="tos-checkbox"
            checked={accepted}
            onCheckedChange={(v) => setAccepted(!!v)}
            data-testid="checkbox-tos-accept"
            className="mt-0.5"
          />
          <span className="text-sm leading-snug select-none">
            I have read and agree to the{" "}
            <strong>Terms of Service</strong> and{" "}
            <strong>Privacy Policy</strong>.
          </span>
        </label>

        {acceptMutation.isError && (
          <p className="text-sm text-destructive" data-testid="text-tos-error">
            Something went wrong. Please try again.
          </p>
        )}

        <Button
          onClick={() => acceptMutation.mutate()}
          disabled={!accepted || acceptMutation.isPending}
          data-testid="button-tos-confirm"
          className="w-full"
        >
          {acceptMutation.isPending ? "Saving…" : "Continue to HolaHola AI"}
        </Button>
      </div>
    </div>
  );
}
