/**
 * fetch-episode-28-gaps.ts
 *
 * Fetches the FULL content of all episode-28 gap rows from DB and writes
 * them to docs/episode-28-gap-analysis.md with classification.
 *
 * Run: npx tsx server/scripts/fetch-episode-28-gaps.ts
 */
import { neon } from '@neondatabase/serverless';
import { writeFileSync } from 'fs';
import { join } from 'path';

const GAP_IDS = [
  'd3c865c5-ab58-42fe-b3f1-aca29b3918a1',
  '16609543-dd72-4ede-bfa9-7958ffc5cdd5',
  '183316ee-7f51-4a06-8dd8-10a9d42cfe41',
  'c2023097-3a6b-4535-876f-916c033efcd8',
  '086d5328-f8f5-4b07-beb0-a0dfae5d260d',
  '5227197b-34a5-4fad-9020-23b9792dc34a',
  '02d32a64-81df-475b-be22-f428af480c48',
  'c99c8912-48d5-48b9-8190-c03c09ecf8fc',
  '60e76d4c-eff7-46bf-87ad-e52a6b000a72',
  '16246a5c-c689-4edf-b6a0-1fcc4884bb37',
  '77f4a242-4886-4b0b-8660-346814a968cb',
  'b21a904b-2522-4d41-8c3a-632aaaf32a50',
  'f460a242-d907-4f4e-a24e-4de7f8f042ef',
  '40171346-22cd-4de1-bfc4-88c3e2c49c81',
  '0010967f-77b5-4861-a277-63a65c341e63',
  '95636fe2-d291-4039-a38b-5ece9ff12a85',
];

async function main() {
  const sql = neon(process.env.DATABASE_URL!);

  const rows = await sql`
    SELECT id, title, content, created_at, tags
    FROM conversation_memories
    WHERE id = ANY(${GAP_IDS}::text[])
    ORDER BY created_at ASC
  `;

  console.log(`Fetched ${rows.length} gap rows`);

  const lines: string[] = [
    '# Episode 28 — Gap Analysis',
    '',
    '*Generated by audit-episode-28-gaps.ts — August 11, 2026*',
    '',
    '## Overview',
    '',
    'The startup-skip bug (task #1023) causes trigger files written before a',
    'server restart to be permanently skipped by the autosave worker.',
    'David caught two missing exchanges at the end of Episode 28.',
    'This audit compares all conversation_memories rows from the Aug 10–11',
    'window against docs/episode-28.md to find every gap.',
    '',
    '## Results',
    '',
    '- **62** real David/Luca exchange rows in DB for the episode window',
    '- **14** CI synthetic rows (excluded)',
    '- **46** rows present in episode-28.md ✓',
    '- **16** rows absent from episode-28.md — listed below',
    '',
    '## Gap Classification',
    '',
    '### Cluster A — Aug 10 19:03–19:29 UTC (live-capture-test session)',
    '',
    'These 5 rows are from a parallel conversation where David and Luca were',
    'testing the chat-capture mechanism against docs/chat-capture-live-test-aug10.md.',
    'They happened during the episode-28 session but were captured to a different',
    '.md. They are real exchanges and belong in the episode record.',
    '',
    '### Cluster B — Aug 11 00:35–01:39 UTC (bug investigation)',
    '',
    'These 10 rows are from a continued debugging session the evening of Aug 11',
    'about fixing the chat-capture cursor and startup-skip bug itself.',
    'These exchanges happened during the episode window and belong in the record.',
    '',
    '### Cluster C — Aug 11 23:23 UTC (postscript)',
    '',
    'One row from the very end of the session — David and Luca sitting while',
    'subagents finish their work. A short closing exchange.',
    '',
    '## Full Gap Content (verbatim)',
    '',
  ];

  for (const row of rows) {
    const at = new Date(row.created_at as string).toISOString();
    const cluster =
      at < '2026-08-11T00:00:00Z' ? 'A' :
      at < '2026-08-11T02:00:00Z' ? 'B' : 'C';

    lines.push(`---`);
    lines.push('');
    lines.push(`**Cluster ${cluster} — DB id: \`${row.id}\` — created_at: ${at}**`);
    lines.push('');
    lines.push('```');
    lines.push((row.content as string).trim());
    lines.push('```');
    lines.push('');
  }

  lines.push('## Next Step');
  lines.push('');
  lines.push('Run `npx tsx server/scripts/audit-episode-28-gaps.ts --patch` to append');
  lines.push('all 16 missing exchanges to episode-28.md in chronological order,');
  lines.push('then sync to DB.');
  lines.push('');

  const outPath = join(process.cwd(), 'docs', 'episode-28-gap-analysis.md');
  writeFileSync(outPath, lines.join('\n'), 'utf-8');
  console.log(`Wrote ${outPath}`);
}

main().catch(e => { console.error(e); process.exit(1); });
